mlflow:
  tracking_url: https://f6f9-2a02-1810-8c09-7d00-c4ef-f014-a6-57da.ngrok-free.app/
  
bucket:
  dev: mlops-models-9876-dev
  prd: mlops-models-9876-prd

model:
  file: model.pkl
  id: "c919bfe952f549738ea07f76720ac44e"
  full_file_name: "c919bfe952f549738ea07f76720ac44e_model.pkl"